id: b3b6bb879b704522ba42ad92999362b5
initial_creation_type: ocr
source_metadata:
  volumes:
    4da2107404224d28a15244bed6a27970:
      base_file: v058.txt
      image_group_id: I1PD95903
      title: དབུ་མའི་སྙིང་པོའི་ཚིག་ལེའུར་བྱས་པ།
      total_pages: 1649
      volume_number: 58
