id: b3b6bb879b704522ba42ad92999362b5
initial_creation_type: ocr
source_metadata:
  volumes:
    ca22fa175cc24b6eb784262ce8ce5811:
      base_file: v057.txt
      image_group_id: I1PD95903
      title: ''
      total_pages: 1649
      volume_number: 58
